# Generated by Django 5.2.5 on 2025-08-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_django_orm', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
