# Generated by Django 5.2.5 on 2025-08-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_django_orm', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media', verbose_name='Изображение'),
        ),
    ]
