# Generated by Django 5.2.5 on 2025-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_django_orm', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='product_image/', verbose_name='Изображение'),
        ),
    ]
