# Generated by Django 5.2.5 on 2025-08-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_text_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
