# Generated by Django 5.2.5 on 2025-10-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_rename_messagereceiver_recipient_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='created_at',
        ),
    ]
