# Generated by Django 5.2.5 on 2025-10-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_remove_mailing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to='messanger.recipient', verbose_name='Получатели'),
        ),
        migrations.CreateModel(
            name='AttemptedMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('succeed', 'Успешно'), ('failed', 'Не успешно')], default='succeed', max_length=20, verbose_name='Статус')),
                ('mail_server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='messanger.mailing', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
