# Generated by Django 5.2.5 on 2025-10-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_alter_mailing_recipients_attemptedmailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedmailing',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='messanger.mailing', verbose_name='Рассылка'),
        ),
    ]
