# Generated by Django 5.2.5 on 2025-09-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'permissions': (('can_change_product_price', 'Can change product price'), ('can_change_product_description', 'Can change product description')), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
